package net.tecgurus.persistence.entities;
// Generated 23/03/2019 01:02:51 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Clientes generated by hbm2java
 */
@Entity
@Table(name = "clientes", catalog = "tec_gurus")
public class Clientes implements java.io.Serializable {

	private Integer idCliente;
	private String nombreCliente;
	private String apellidoPCliente;
	private String apellidoMCliente;
	private String telefono;
	private String email;

	public Clientes() {
	}

	public Clientes(String nombreCliente, String apellidoPCliente) {
		this.nombreCliente = nombreCliente;
		this.apellidoPCliente = apellidoPCliente;
	}

	public Clientes(String nombreCliente, String apellidoPCliente, String apellidoMCliente, String telefono,
			String email) {
		this.nombreCliente = nombreCliente;
		this.apellidoPCliente = apellidoPCliente;
		this.apellidoMCliente = apellidoMCliente;
		this.telefono = telefono;
		this.email = email;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_cliente", unique = true, nullable = false)
	public Integer getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(Integer idCliente) {
		this.idCliente = idCliente;
	}

	@Column(name = "nombre_cliente", nullable = false, length = 100)
	public String getNombreCliente() {
		return this.nombreCliente;
	}

	public void setNombreCliente(String nombreCliente) {
		this.nombreCliente = nombreCliente;
	}

	@Column(name = "apellido_p_cliente", nullable = false, length = 100)
	public String getApellidoPCliente() {
		return this.apellidoPCliente;
	}

	public void setApellidoPCliente(String apellidoPCliente) {
		this.apellidoPCliente = apellidoPCliente;
	}

	@Column(name = "apellido_m_cliente", length = 100)
	public String getApellidoMCliente() {
		return this.apellidoMCliente;
	}

	public void setApellidoMCliente(String apellidoMCliente) {
		this.apellidoMCliente = apellidoMCliente;
	}

	@Column(name = "telefono", length = 50)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Override
	public String toString() {
		return "Clientes [idCliente=" + idCliente + ", nombreCliente=" + nombreCliente + ", apellidoPCliente="
				+ apellidoPCliente + ", apellidoMCliente=" + apellidoMCliente + ", telefono=" + telefono + ", email="
				+ email + "]";
	}

	
	
}
